## Working with numpy - basic operations

In [1]:
import numpy as np

In [2]:
a = np.array([1,2,3,4,5])

In [3]:
a


array([1, 2, 3, 4, 5])

In [4]:
type(a)

numpy.ndarray

In [5]:
a.shape

(5,)

In [10]:
b = np.array([[1],[2],[3],[4],[5]])

In [11]:
print(b)

[[1]
 [2]
 [3]
 [4]
 [5]]


In [12]:
b

array([[1],
       [2],
       [3],
       [4],
       [5]])

In [13]:
print(b.shape)

(5, 1)


In [14]:
b[0][0]

1

In [15]:
c = np.zeros((2,2))

In [16]:
print(c)

[[0. 0.]
 [0. 0.]]


In [17]:
d = np.ones((3,3))
print(d)


[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [18]:
d = np.ones(3)
print(d)

[1. 1. 1.]


In [21]:
e = np.full((1,3),5)
print(e)
print(e.shape)

[[5 5 5]]
(1, 3)


In [20]:
e = np.full(3,5)
print(e)
print(e.shape)

[5 5 5]
(3,)


In [22]:
f = np.random.random((3,3))
print(f)


[[0.57005069 0.24688729 0.97443861]
 [0.95262309 0.51782032 0.67440415]
 [0.50069554 0.87529833 0.02342784]]


In [23]:
print(f[:,1])

[0.24688729 0.51782032 0.87529833]


In [24]:
f[1,:] = 3
print(f)

[[0.57005069 0.24688729 0.97443861]
 [3.         3.         3.        ]
 [0.50069554 0.87529833 0.02342784]]


In [35]:
a = np.array([[1,2,3],[4,5,6]])
b = np.array([[7,8,9],[10,11,12]])
print(a*b)

[[ 7 16 27]
 [40 55 72]]


In [26]:
print(a+b)


[[ 8 10 12]
 [14 16 18]]


In [27]:
np.sum(a)

21

In [29]:
type(np.sum(a,axis=1))

numpy.ndarray

In [33]:
print(np.sum(a,axis=1))

[ 6 15]


In [34]:
a.dot(b)

ValueError: shapes (2,3) and (2,3) not aligned: 3 (dim 1) != 2 (dim 0)

In [36]:
a.dot(b)

ValueError: shapes (2,3) and (2,3) not aligned: 3 (dim 1) != 2 (dim 0)

In [37]:
b = np.array([[1,2],[2,3],[4,5]])

In [38]:
a.dot(b)


array([[17, 23],
       [38, 53]])

In [39]:
np.dot(a,b)

array([[17, 23],
       [38, 53]])

In [40]:
a = np.random.random((3,2))

In [41]:
a


array([[0.74097479, 0.75100154],
       [0.08871157, 0.67391507],
       [0.04358694, 0.25377695]])

In [42]:
a = np.random.random(3,2)

TypeError: random_sample() takes at most 1 positional argument (2 given)

In [43]:
a = np.random.randn(3,2)


In [44]:
a


array([[ 0.76205029,  0.09238885],
       [ 0.88600014, -1.03936928],
       [-0.00906498, -1.48266439]])

In [45]:
a = np.random.randn((3,2))

TypeError: 'tuple' object cannot be interpreted as an integer

In [46]:
a = np.arange(10)

In [47]:
a


array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [48]:
print(np.random.shuffle(a))

None


In [58]:

a = np.arange(10)
np.random.shuffle(a)
print(a)

[8 3 5 9 0 6 1 7 4 2]


In [59]:
a = np.arange(10)


In [60]:
print(a)


[0 1 2 3 4 5 6 7 8 9]


In [61]:
a-5

array([-5, -4, -3, -2, -1,  0,  1,  2,  3,  4])